.\" Title of the manual page
.TH VECTOR_PUSHBACK 3 "April 12, 2023" "Version 1.0" "Vector Library By Axel"

.\" Name section
.SH NAME
vector_pushback \- Adds an element to the end of the vector.

.\" Synopsis section
.SH SYNOPSIS
.B #include <vector.h>
.PP
.B void vector_pushback(vector_t *vector, const void *data);

.\" Description section
.SH DESCRIPTION
The function
.B vector_pushback()
adds an element to the end of the
.I vector
by copying the data from the given
.I data
pointer. The
.I data
pointer should point to the address of the element, not the element itself.

.\" Parameters section
.SH PARAMETERS
.TP
.B vector
A pointer to the vector.
.TP
.B data
A pointer to the address of the element to be added to the vector.

.\" Return Value section
.SH "RETURN VALUE"
The function
.B vector_pushback()
does not return a value.

.\" Example section
.SH EXAMPLE
Here is an example of using the `vector_pushback` function to add a string to a vector of strings:

.PP
.RS
.nf
#include "vector.h"

int main(void)
{
    vector_t *vector = vector_create(10, sizeof(char *));
    // Use the vector to store strings
    // ...

    // Add a string to the vector
    char *new_str = "example";
    vector_pushback(vector, &new_str);

    // Free the vector
    vector_free(&vector);
    return 0;
}
.fi
.RE

.\" See Also section
.SH "SEE ALSO"
.IR vector_create (3),
.IR vector_at (3),
.IR vector_popback (3),
.IR vector_free (3)
